# ASP.NET Core (.NET Framework)
# Build and test ASP.NET Core projects targeting the full .NET Framework.
# Add steps that publish symbols, save build artifacts, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

trigger:
- main

pool:
  vmImage: 'windows-latest'

variables:
  solution: '**/*.sln'
  buildPlatform: 'Any CPU'
  buildConfiguration: 'Release'
  driverFolder: 'searchTest\searchTest\webdriver'
  driverVersionUrl: 'https://chromedriver.storage.googleapis.com/LATEST_RELEASE_'
  webdriverUrl: 'https://chromedriver.storage.googleapis.com'
  chromedriverZip: 'chromedriver_win32.zip'

steps:
- task: NuGetToolInstaller@1

- task: NuGetCommand@2
  inputs:
    restoreSolution: '$(solution)'

- task: PowerShell@1
  displayName: GetWebdriver

  inputs:
   scriptType: inlineScript
   inlineScript: >-
      $chromeVersion = (Get-Item (Get-ItemProperty 'HKLM:\SOFTWARE\Microsoft\Windows\CurrentVersion\App Paths\chrome.exe').'(Default)').VersionInfo.ProductVersion; 
      $chromeVersionSplit = chromeVersion -split({$_ -eq "."});
      $chromeVersion = ($chromeVersionSplit[0..2] -join '.');
      $chromeVersion = Invoke-RestMethod -Uri "$(driverVersionUrl)$chromeVersion";
      Write-Host "$chromeVersion";
      $downloadUrl = "$(webdriverUrl)/$chromeVersion/$(chromedriverZip)";
      Write-Host "Url : $downloadUrl -- Fazendo download";
      Invoke-WebRequest -Uri "$downloadUrl"  -OutFile "$(Build.Repository.LocalPath)\$(driverFolder)\$(chromedriverZip)";
      Expand-Archive -Path "$(Build.Repository.LocalPath)\$(driverFolder)\$(chromedriverZip)" -DestinationPath "$(Build.Repository.LocalPath)\$(driverFolder)" -Force;
      cd "$(Build.Repository.LocalPath)";
      cd "searchTest";
      cd "searchTest";
      cd "webdriver";
      ls;
      Write-Host "Download concluído";
      Write-Host "folder : $(Build.Repository.LocalPath)\$(driverFolder)\$(chromedriverZip)";
      
      
- task: VSBuild@1
  inputs:
    solution: '$(solution)'
    msbuildArgs: '/p:DeployOnBuild=true /p:WebPublishMethod=Package /p:PackageAsSingleFile=true /p:SkipInvalidConfigurations=true /p:DesktopBuildPackageLocation="$(build.artifactStagingDirectory)\WebApp.zip" /p:DeployIisAppPath="Default Web Site"'
    platform: '$(buildPlatform)'
    configuration: '$(buildConfiguration)'

- task: VSTest@2
  inputs:
    testSelector: 'testAssemblies'
    testAssemblyVer2: |
      **\searchTest.dll
      !**\*TestAdapter.dll
      !**\obj\**
    searchFolder: '$(System.DefaultWorkingDirectory)'
